languageCode = 'en-us'
title = 'Path to my memory'
theme = 'hugo-theme-relearn'

[params]
  themeVariant = ['auto', 'relearn-dark', 'relearn-light', 'zen-dark', 'zen-light']
  themeVariantAuto = [ "relearn-dark", "relearn-light" ]   

#
# following allow embed html tag into the markdown
#
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

#
# enable landing page Home in English.
#
[languages]
[languages.en]
[languages.en.params]
landingPageName = "<i class='fas fa-home'></i> Home"

[params.logo]
   src = '/images/large_tiger.gif'

   
